-- AlterTable
ALTER TABLE "snipe_configs" ADD COLUMN     "entryFilterEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxTop10HolderPercent" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "minBuySellRatio" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "minHolderCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "minRecentVolumeUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
